### ISSUE TITLE
Add memcached

### ISSUE THREAD

**Issue by olofjohansson** [oddhill/oddboxen#740]
Investigate whether or not it's a good idea to add memcached integration with PHP.

Is this bad from a development perspective? What could be the benefits? How should it be accomplished? Provided as a service just like apache, mysql etc? This way we could maybe turn it off if we don't want it for a particular project or something.

**Comment by jenslind** [comment]
I don't see why it would be a bad idea.
What we need:
- The memcached daemon
- memcached php extension

The daemon will be running as a boxen service. So it will be easy to turn on/off. Also we could have it off by default, because it will most likely only be some specific sites that needs the memcache daemon to be running.

:mag:
